services:
  - type: web
    name: heart-disease-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: PORT
        value: 8000
